config/routes.rb
Rails.application.routes.draw do
  resources :media do
    resources :comments
  end
  root 'pages#home'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :medium
end

app/models/medium.rb
class Medium < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :media
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    medium = Medium.find(params[:medium_id])
    @comment = medium.comments.build
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    medium = Medium.find(params[:medium_id])
    @comment = medium.comments.build(comment_params)
    @comment.user_id = current_user.id

    respond_to do |format|
      if @comment.save
        format.html { redirect_to medium_path(medium), notice: 'Comment was successfully created.' }
        # format.json { render :show, status: :created, location: medium_comment_path(@comment) }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to medium_comments_path(@comment.medium), notice: 'Comment was successfully updated.' }
        # format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to medium_comments_path(@comment.medium), notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content, :user_id, :medium_id)
    end
end

app/controllers/media_controller.rb
class MediaController < ApplicationController
  before_action :set_medium, only: [:show, :edit, :update, :destroy]

  # GET /media
  # GET /media.json
  def index
    @media = Medium.all
  end

  # GET /media/1
  # GET /media/1.json
  def show
  end

  # GET /media/new
  def new
    @medium = current_user.media.build
  end

  # GET /media/1/edit
  def edit
  end

  # POST /media
  # POST /media.json
  def create
    @medium = current_user.media.build(medium_params)
    respond_to do |format|
      if @medium.save
        format.html { redirect_to @medium, notice: 'Medium was successfully created.' }
        format.json { render :show, status: :created, location: @medium }
      else
        format.html { render :new }
        format.json { render json: @medium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /media/1
  # PATCH/PUT /media/1.json
  def update
    respond_to do |format|
      if @medium.update(medium_params)
        format.html { redirect_to @medium, notice: 'Medium was successfully updated.' }
        format.json { render :show, status: :ok, location: @medium }
      else
        format.html { render :edit }
        format.json { render json: @medium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /media/1
  # DELETE /media/1.json
  def destroy
    @medium.destroy
    respond_to do |format|
      format.html { redirect_to media_url, notice: 'Medium was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medium
      @medium = Medium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medium_params
      params.require(:medium).permit(:image_data, :description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @media = Medium.order('created_at DESC').limit(10)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/media_helper.rb
module MediaHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment, url: medium_comments_path) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :comment_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/_form_update.html.erb
<%= form_for(@comment, url: medium_comment_path) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :comment_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form_update', comment: @comment %>

<%= link_to 'Show', medium_comment_path(@comment.medium, @comment) %> |
<%= link_to 'Back', medium_comments_path(@comment.medium) %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th>Medium</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.content %></td>
        <td><%= comment.user.email %></td>
        <td><%= comment.medium %></td>
        <td><%= link_to 'Show', medium_comment_path(comment.medium, comment) %></td>
        <td><%= link_to 'Edit', edit_medium_comment_path(comment.medium, comment) %></td>
        <td><%= link_to 'Destroy', medium_comment_path(comment.medium, comment), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_medium_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', root_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Medium:</strong>
  <%= @comment.medium %>
</p>


<%= link_to 'Back', medium_comments_path %>

app/views/layouts/_footer.html.erb
<footer>
  Copyright Instarails 2018
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <%= link_to 'Instarails', root_path, class: "navbar-brand" %>    
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">        
            <%= link_to 'Sign-Out', destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#"><%= current_user.email%></a>
          </li>
        <% else %>
          <li class="nav-item">      
            <%= link_to 'Register', new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">        
            <%= link_to 'Sign-In', new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instarails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
  
    <main>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>
    </main>

    <%= render 'layouts/footer' %>
    
  </body>
</html>

app/views/media/_form.html.erb
<%= form_with(model: medium, local: true) do |form| %>
  <% if medium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(medium.errors.count, "error") %> prohibited this medium from being saved:</h2>

      <ul>
      <% medium.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image_data %>
    <%= form.text_area :image_data, id: :medium_image_data %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :medium_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/media/_media.html.erb
<% @media.each do |medium|%>
  <div class="card" style="width: 36rem;">
    <%= link_to image_tag(medium.image_data, class: "card-img-top"), medium_path(medium) %>
    <div class="card-body">
      <%# <h5 class="card-title">Card title</h5> %>
      <p class="card-text"><strong><%= medium.user.email %></strong>: <%= medium.description %></p>
      <p class="card-text"><small><%= "#{time_ago_in_words(medium.created_at)} ago" %></small></p>      
    </div>
    <ul class="list-group list-group-flush">
      <% medium.comments.each do |comment|%>
        <li class="list-group-item"><strong><%= comment.user.email %></strong>: <%= comment.content %></li>
      <% end %>
    </ul>
    <div class="card-body">
      <%= link_to 'Comment', new_medium_comment_path(medium) %>
    </div>
  </div>
  <br>
<% end %>

app/views/media/edit.html.erb
<h1>Editing Medium</h1>

<%= render 'form', medium: @medium %>

<%= link_to 'Show', @medium %> |
<%= link_to 'Back', media_path %>

app/views/media/index.html.erb
<h1>Media</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @media.each do |medium| %>
      <tr>
        <td><%= medium.description %></td>
        <td><%= medium.user.email %></td>
        <td><%= link_to 'Show', medium %></td>
        <td><%= link_to 'Edit', edit_medium_path(medium) %></td>
        <td><%= link_to 'Destroy', medium, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Medium', new_medium_path %>

app/views/media/new.html.erb
<h1>New Medium</h1>

<%= render 'form', medium: @medium %>

<%= link_to 'Back', media_path %>

app/views/media/show.html.erb
<div class="container" style="width: 600px;">
  <p>
    <%= image_tag @medium.image_data, width: 200 %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @medium.description %>
  </p>

  <p>
    <strong>User:</strong>
    <%= @medium.user.email %>
  </p>

  <ul>
  <% @medium.comments.each do |comment| %>
    <li><%= comment.user.email %>: <%= comment.content %></li>
  <% end %>
  </ul>

  <%= link_to 'Comment', new_medium_comment_path(@medium) %>

  <%= link_to 'Edit', edit_medium_path(@medium) %> |
  <%= link_to 'Back', root_path %>
</div>

app/views/pages/home.html.erb
<div class="container" style="width: 600px;">
  <div>
    <%= link_to 'Post something!', new_medium_path, class:"btn btn-primary btn-lg btn-block" %>
  </div>
  <br>

  <%= render 'media/media', media: @media %>
</div>